Repository szabobatony/Rajongoi9A-C, pull requests merged in 2024-03, with the labels that each got.

#22 Javítás 2
  index.html
  tortenet.html
Labels: bug

#23 Javítás 3
  index.html
  kviz.html
  tortenet.html
Labels: helytelen

#26 kvíz fix
  index.html
  jatekosok.html
  kviz.html
  képek/3Védők/BALOGH BOTOND.png
  képek/3Védők/BOLLA BENDEGÚZ.png
  képek/3Védők/BOTKA ENDRE.png
  képek/3Védők/KERKEZ MILOS.png
  képek/3Védők/LANG ÁDÁM.png
  képek/3Védők/MOCSI ATTILA.png
  képek/3Védők/NAGY ZSOLT.png
  képek/3Védők/SZALAI ATTILA.png
  képek/3Védők/SZALAI GÁBOR.png
  tortenet.html
Labels: dokumentáció

#40 kvíz fix
  kviz.html
  képek/9Kvíz/hatter.jpg
Labels: dokumentáció

#50 Elérhetőségek
  Rólunk/Skulec Dávid/mas.png
  Rólunk/Skulec Dávid/masik.png
  Rólunk/Skulec Dávid/social.txt
  Rólunk/Szabó Bátony/batony.png.jpg
  rolunk.html
Labels: dokumentáció
